CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(40) NOT NULL,
	`externalReference` varchar(80) NOT NULL,
	`paymentId` varchar(64),
	`status` enum('creating_payment','awaiting_payment','paid','processing','shipped','delivered','payment_failed','canceled','refunded') NOT NULL DEFAULT 'creating_payment',
	`productId` varchar(80) NOT NULL,
	`productTitle` varchar(240) NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`originalPriceCents` int NOT NULL,
	`discountPercent` int NOT NULL DEFAULT 10,
	`totalCents` int NOT NULL,
	`customerName` varchar(160) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(24) NOT NULL,
	`postalCode` varchar(9) NOT NULL,
	`street` varchar(180) NOT NULL,
	`addressNumber` varchar(20) NOT NULL,
	`complement` varchar(120),
	`neighborhood` varchar(100) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`consentTerms` boolean NOT NULL DEFAULT false,
	`consentPrivacy` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`),
	CONSTRAINT `orders_externalReference_unique` UNIQUE(`externalReference`)
);
