export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mercadoPagoAccessToken: process.env.MERCADOPAGO_ACCESS_TOKEN ?? "",
  publicSiteUrl: process.env.PUBLIC_SITE_URL ?? "https://protesecapilar.tech",
  directSalesEnabled: (process.env.DIRECT_SALES_ENABLED ?? "").trim().toLowerCase() === "true",
  sellerLegalName: process.env.SELLER_LEGAL_NAME ?? "",
  sellerTaxId: process.env.SELLER_TAX_ID ?? "",
  sellerSupportEmail: process.env.SELLER_SUPPORT_EMAIL ?? "",
  directSalesShippingEstimate: process.env.DIRECT_SALES_SHIPPING_ESTIMATE ?? "",
};
